# -*- coding: utf-8 -*-
"""비인기지역탐색.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zABOXteursousMi2gOwLNKx_XCJgXHeF
"""

import pandas as pd

visitors = pd.read_excel('/content/광역별 외국인 방문자 수 .xlsx')
expenditures = pd.read_excel('/content/광역별 외국인 지출 통계.xlsx')

def rename(df):
  duplicates = df[df.duplicated(subset=['기초지자체명'], keep=False)]
  for name in duplicates['기초지자체명'].unique():
    mask = (df['기초지자체명'] == name)
    df.loc[mask, '기초지자체명'] = [f"{name}_{i+1}" for i in range(mask.sum())]
  return df

  visitors = rename(visitors)
  expenditures = rename(expenditures)

data = pd.merge(visitors, expenditures, on=['광역지자체명','기초지자체명'])

print(data.head())

excluded_regions = ['서울특별시', '경기도']
filtered_data = data[~data['광역지자체명'].isin(excluded_regions)]

print(filtered_data.head())

columns_to_drop = ['광역지자체 방문자 수', '광역지자체 방문자 비율', '광역지자체 지출액', '광역지자체 지출액 비율']
filtered_data.drop(columns=columns_to_drop, inplace=True)

print(filtered_data.head())

median_visitors = filtered_data['기초지자체 방문자 수'].median()
median_expenditures = filtered_data['기초지자체 방문자 수'].median()

unpopular_regions = filtered_data[(filtered_data['기초지자체 방문자 수'] <= median_visitors) & (filtered_data['기초지자체 지출액'] <= median_expenditures)]

print(unpopular_regions)

average_visitors = filtered_data['기초지자체 방문자 수'].mean()
average_expenditures = filtered_data['기초지자체 방문자 수'].mean()

unpopular_regions = filtered_data[(filtered_data['기초지자체 방문자 수'] <= average_visitors) & (filtered_data['기초지자체 지출액'] <= average_expenditures)]

print(unpopular_regions)